### ISSUE TITLE
Let's win a Tshirt! #Hacktoberfest

### ISSUE THREAD

**Issue by reciomario** [reciomario/coursera_exercises#1]
This issue has been created to ilustrate the contribution process about creating a new pull-request, accepting it and... **Applying for a Github Tshirt!**
+Info [Hacktoberfest](https://hacktoberfest.digitalocean.com/)

I will accept New pull-requests modifying the list of programming languages proposed in this Scala-Spark example **spark03stackoverflow/StackOverflow.scala"**.

Fork the project, create a new branch, and try to modify this list and execute the app to check what happens!
```sh
val langs = List("JavaScript", "Java", "PHP", "Python", "C#", "C++", "Ruby", "CSS", "Objective-C", "Perl", "Scala", "Haskell", "MATLAB", "Clojure", "Groovy")
```

**Comment by JWesorick** [comment]
🎉

**Comment by shaido987** [comment]
#7

**Comment by shaido987** [comment]
[**Added Erlang and Ada** \#7](#7)
